#PR_TITLE_REGEX: /[a-z][a-z]/i
#COMMIT_MESSAGE_REGEX: /[a-z]/i
PR_TITLE_REGEX: /.*/
COMMIT_MESSAGE_REGEX: /^(feat|fix|test|design|refactor|setup|docs|import|revert)(\([a-z ]+\))?:\t[a-z\d _\-\.\(\)\/\\"'%&$<>!#*]+(\n.*)*/
